package domain;
// Generated 29-mar-2018 23:18:01 by Hibernate Tools 5.2.8.Final

/**
 * Usuarios generated by hbm2java
 */
@SuppressWarnings("serial")
public class Usuarios implements java.io.Serializable {

	private Integer idusuario;
	private String username;
	private String password;
	private Integer puntos;

	public Usuarios() {
	}

	public Usuarios(String username, String password, Integer puntos) {
		this.username = username;
		this.password = password;
		this.puntos = puntos;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Integer puntos) {
		this.puntos = puntos;
	}

}
